
.PHONY: run clean build

run:
	[command] ./{{ module_slug }}/main.{{ project_language }}

build:
	[command] ./{{ module_slug }}/main.{{ project_language }}

clean:
	[command] ./{{ module_slug }}/main.{{ project_language }}

